massive002/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Index page
    (r'', include('gmapi.urls.media')),
    url(r'^$', 'engine.views.index', name='index'),
    url(r'^contato/$', 'engine.views.contato', name='contatos'),

    # Login/logout
    url(r'^usuario/registrar/$', 'engine.views.registra_usuario', name='user_signup'),
    url(r'^usuario/login/$', 'engine.views.login_usuario', name='login_usuario'),
    url(r'^usario/logout/$', 'engine.views.logout_usuario', name='logout_usuario'),

    # Admin
    url(r'^man/', include(admin.site.urls)),
   # url('^setup/$', 'massivecoupon.socialregistration.views.setup', name='socialregistration_setup'),
   # url('^logout/$', 'massivecoupon.socialregistration.views.logout', name='social_logout'),

    # Static stuff (apache should serve this in production)
    (r'^(robots.txt)$', 'django.views.static.serve', {'document_root': '/var/www/massivecoupon/'}),
)
#((r'^media/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.MEDIA_ROOT})),
if settings.LOCAL:
    urlpatterns = urlpatterns + patterns('',
        ((r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT})),
        ((r'^geoip/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.GEOIP_PATH})),
        )


# Setup Facebook URLs if there's an API key specified
#if getattr(settings, 'FACEBOOK_API_KEY', None) is not None:
#    urlpatterns = urlpatterns + patterns('',
#        url('^facebook/login/$', 'massivecoupon.socialregistration.views.facebook_login',
#            name='facebook_login'),
#
#        url('^facebook/connect/$', 'massivecoupon.socialregistration.views.facebook_connect',
#            name='facebook_connect'),
#
#        url('^xd_receiver.htm', 'django.views.generic.simple.direct_to_template',
#            {'template':'socialregistration/xd_receiver.html'},
#            name='facebook_xd_receiver'),
#    )
#
##Setup Twitter URLs if there's an API key specified
#if getattr(settings, 'TWITTER_CONSUMER_KEY', None) is not None:
#    urlpatterns = urlpatterns + patterns('',
#        url('^twitter/redirect/$', 'massivecoupon.socialregistration.views.oauth_redirect',
#            dict(
#                consumer_key=settings.TWITTER_CONSUMER_KEY,
#                secret_key=settings.TWITTER_CONSUMER_SECRET_KEY,
#                request_token_url=settings.TWITTER_REQUEST_TOKEN_URL,
#                access_token_url=settings.TWITTER_ACCESS_TOKEN_URL,
#                authorization_url=settings.TWITTER_AUTHORIZATION_URL,
#                callback_url='twitter_callback'
#            ),
#            name='twitter_redirect'),
#
#        url('^twitter/callback/$', 'socialregistration.views.oauth_callback',
#            dict(
#                consumer_key=settings.TWITTER_CONSUMER_KEY,
#                secret_key=settings.TWITTER_CONSUMER_SECRET_KEY,
#                request_token_url=settings.TWITTER_REQUEST_TOKEN_URL,
#                access_token_url=settings.TWITTER_ACCESS_TOKEN_URL,
#                authorization_url=settings.TWITTER_AUTHORIZATION_URL,
#                callback_url='twitter'
#            ),
#            name='twitter_callback'
#        ),
#        url('^twitter/$', 'socialregistration.views.twitter', name='twitter'),
#    )
#
## Setup FriendFeed URLs if there's an API key specified
#if getattr(settings, 'FRIENDFEED_CONSUMER_KEY', None) is not None:
#    urlpatterns = urlpatterns + patterns('',
#        url('^friendfeed/redirect/$', 'socialregistration.views.oauth_redirect',
#            dict(
#                consumer_key=settings.FRIENDFEED_CONSUMER_KEY,
#                secret_key=settings.FRIENDFEED_CONSUMER_SECRET_KEY,
#                request_token_url=settings.FRIENDFEED_REQUEST_TOKEN_URL,
#                access_token_url=settings.FRIENDFEED_ACCESS_TOKEN_URL,
#                authorization_url=settings.FRIENDFEED_AUTHORIZATION_URL,
#                callback_url='friendfeed_callback'
#            ),
#            name='friendfeed_redirect'),
#
#        url('^friendfeed/callback/$', 'socialregistration.views.oauth_callback',
#            dict(
#                consumer_key=settings.FRIENDFEED_CONSUMER_KEY,
#                secret_key=settings.FRIENDFEED_CONSUMER_SECRET_KEY,
#                request_token_url=settings.FRIENDFEED_REQUEST_TOKEN_URL,
#                access_token_url=settings.FRIENDFEED_ACCESS_TOKEN_URL,
#                authorization_url=settings.FRIENDFEED_AUTHORIZATION_URL,
#                callback_url='friendfeed'
#            ),
#            name='friendfeed_callback'
#        ),
#        url('^friendfeed/$', 'massivecoupon.socialregistration.views.friendfeed', name='friendfeed'),
#    )
#
#urlpatterns = urlpatterns + patterns('',
#    url('^openid/redirect/$', 'massivecoupon.socialregistration.views.openid_redirect',
#        name='openid_redirect'),
#    url('^openid/callback/$', 'massivecoupon.socialregistration.views.openid_callback',
#        name='openid_callback')
#)

urlpatterns = urlpatterns + patterns('',
    url(r'^(?P<cidade_slug>\w+)/$', 'engine.views.cidade_index', name='cidade_index'),
    
    url(r'^(?P<cidade_slug>\w+)/assinar/$', 'engine.views.inscricao_cidade',
        name='city_subscribe'),
                                     
    url(r'^(?P<cidade_slug>\w+)/(?P<oferta_slug>[-\w]+)/$',
        'engine.views.oferta_detalhe', name='oferta_detalhe'),
                                     
    url(r'^(?P<cidade_slug>\w+)/(?P<oferta_slug>[-\w]+)/(?P<quantidade>\d+)/checkout/completo/$',
        'engine.views.oferta_checkout_complete', name='oferta_checkout_complete'),
                                     
    url(r'^(?P<cidade_slug>\w+)/(?P<oferta_slug>[-\w]+)/comprar/$',
        'engine.views.oferta_checkout', name='oferta_checkout'),
      
                                     
#    (r'^ofertas/(?P<cidade>[-\w]+)/$',
#     'show_oferta_cidade', {
#     'nome_template':'catalogo/cidade.html'},'catalogo_cidade'),
#    (r'^ofertas/(?P<cidade>[-\w]+)/(?P<oferta_slug>[-\w]+)/$',
#     'show_oferta', {
#     'nome_template':'catalogo/oferta.html'},'catalogo_oferta'),
#     (r'^email/$', 'amigoForm',{ 'nome_template':'catalogo.html' }, 'emailAmigo'),
)

massive002/engine/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models  # Replaced by models in gis package
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.utils.translation import ugettext_lazy as _
from django.utils.dates import WEEKDAYS
from django.core.urlresolvers import reverse
import time
from massive002.photologue.models import TagField

#from massivecoupon.photologue.models import ImageModel
#from massivecoupon.countries.models import Country
#from massive.photologue.models import TagField

OFERTA_IMG = 'ofertas_imagens/'
OFERTA_MINI = 'ofertas_mini/'

STATUS_EMESPERA = 1
STATUS_ATIVO = 2
STATUS_CANCELADO = 3

STATUS = (
  (STATUS_EMESPERA, "Comprado - Em Espera"),
  (STATUS_ATIVO, "Comprado - Pegou o dinheiro"),
  (STATUS_CANCELADO, "Nao efetuada a compra"),
)


CC_VISA = 1
CC_MASTERCARD = 2
CC_AMEX = 3

CC_TIPO = (
  (CC_VISA, 'Visa'),
  (CC_VISA, 'Mastercard'),
  (CC_AMEX, 'American Express'),
)

class Estado(models.Model):
    """
    Localizacao do bairro (latitude, longitude, cep)
    """
    class Meta:
        verbose_name = _('Estado')
        verbose_name_plural = _('Estados')

    nome = models.CharField(verbose_name=_("Nome"), max_length=60)
    #estado = models.ForeignKey("estado.Estado", null=True, blank=True)

    def __unicode__(self):
        return self.nome

class Cidade(models.Model):
    """
     Localizacao do bairro (latitude, longitude, cep)
    """
    class Meta:
        verbose_name = 'Cidade'
        verbose_name_plural = 'Cidades'

    nome = models.CharField(verbose_name=_("Nome"), max_length=60)
    slug = models.SlugField(db_index=True)
    ativo = models.BooleanField(default=False, db_index=True)
    estado = models.ForeignKey("Estado", null=True, blank=True)
    pedido = models.IntegerField(default=0, db_index=True)

    def __unicode__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('cidade_index', kwargs={'cidade_slug': self.pk})

class Anunciante(models.Model):
    class Meta:
        verbose_name = _('Anunciante')
        verbose_name_plural = _('Anunciantes')

    nome       = models.CharField(max_length=60)
    endereco    = models.CharField(max_length=60)
    cidade       = models.ForeignKey(Cidade)
    cep = models.CharField(max_length=7)
    estado    = models.ForeignKey(Estado)
    telefone      = models.CharField(max_length=25)
    telefone_extra   = models.CharField("Telefone Extra", max_length=6, blank=True)
    celular       = models.CharField(max_length=25)
    fax        = models.CharField(max_length=25)
    contato    = models.CharField(max_length=50, blank=True, help_text="Contato do anunciante")
    email      = models.EmailField(blank=True, help_text="Email do contato")
    website    = models.URLField(blank=True, verbose_name=_('Website'))

    def __str__(self):
        return self.nome
    class Admin:
        list_display = ( "nome", "contato", "email", "telefone" )

class CategoriaOfertas(models.Model):
    """
    Categorias de varias ofertas
    """

    class Meta:
        verbose_name = _('Categoria')
        verbose_name_plural = _('Categorias')

    nome = models.CharField("Categoria", max_length=60)

    def __unicode__(self):
        return self.nome

class OfertaManager(models.Manager):
    def ativa_na_cidade(self, cidade):
        qs = self.get_query_set()

        # Filter by city
        qs = qs.filter(cidade=cidade)

        # Only the active ones
        qs = qs.filter(ativo=True)

        # Only up to date
        qs = qs.filter(finaliza_em__gte=datetime.datetime.now())

        # Order with the featured deal first
        qs = qs.order_by('-estreando')

        return qs

class Oferta(models.Model):
    """
    Actual services
    """
    class Meta:
        verbose_name = _('Oferta')
        verbose_name_plural = _('Oferta')

    objects = _default_manager = OfertaManager()

    anunciante              = models.ForeignKey(Anunciante)
    cidade                  = models.ForeignKey(Cidade, related_name='ofertas')
    titulo                  = models.CharField(verbose_name=_("Titulo"), max_length=256)
    subtitulo                  = models.CharField(verbose_name=_("SubTitulo"), max_length=256)
    
    slug                    = models.SlugField(db_index=True)

    categoria                = models.ForeignKey(CategoriaOfertas)

    publicado_em            = models.DateTimeField(blank=True, auto_now_add=True, db_index=True)
    inicia_em              = models.DateTimeField(blank=True, null=True, db_index=True)
    # The field 'date_end' could be synchronized with 'auction_duration'
    finaliza_em                = models.DateTimeField(blank=True, null=True, db_index=True)

    preco_varejo            = models.DecimalField(default=0,decimal_places=2, max_digits=6, help_text='Full retail price')
    preco_oferta              = models.DecimalField(default=0,decimal_places=2, max_digits=6, help_text='Deal (real) Price')

    porcentagem_desconto     = models.DecimalField(default=0,decimal_places=2, max_digits=6, help_text='% Percentage Off retail')
    valor_desconto          = models.DecimalField(default=0,decimal_places=2, max_digits=6, help_text='$ Dollars Off retail')

    duracao_da_oferta        = models.IntegerField(default=24, help_text=_('Deal duration in hours'))
    
    destaque              = models.BooleanField(default=False, db_index=True)
    ativo              = models.BooleanField(default=True, db_index=True)
    estreando                = models.BooleanField(default=False, db_index=True)

    sobre_oferta              = models.TextField()
    destaque_oferta              = models.TextField()

    

    qtd_ofertas_disponiveis           = models.IntegerField(default=1)
    qtd_ofertas_por_pessoa = models.IntegerField(default=1)
    qtd_ofertas_vendidas           = models.IntegerField(default=1)

    descricao_completa             = models.TextField()
    descricao_resumida             = models.TextField()
    
    qtd_fechamento = models.IntegerField(default=0)
    data_fechamento = models.DateTimeField()
    #  reviews                 = models.TextField()

    descricao_compania            = models.TextField()
    #  address                 = models.TextField()

    #  url                     = models.URLField()
   
    imagem                   = models.ImageField(upload_to='ofertas_imagems/', blank=True)
    miniatura                   = models.ImageField(upload_to='ofertas_mini/', blank=True)

    tags                    = TagField(help_text=_("Tags devem ser separados por virgula"), verbose_name=_('Tags'))

    latitude = models.DecimalField(
            verbose_name=_("Latitude (decimal)"),
            max_digits=9,
            decimal_places=6,
            blank=True,
            null=True,
            )
    longitude = models.DecimalField(
            verbose_name=_("Longitude (decimal)"),
            max_digits=9,
            decimal_places=6,
            blank=True,
            null=True,
            )
    meta_keywords = models.CharField("Meta Keywords", max_length=255,
                                     help_text=u'Conjunto delimitado por virgulas de palavras-chave para SEO meta tag')
    meta_description = models.CharField("Meta Description", max_length=255,
                                        help_text=u'Descricao da meta-tag')

    data_entrada              = models.DateTimeField(blank=True, editable=False, null=True, auto_now_add=True)
    data_modificacao              = models.DateTimeField(blank=True, editable=False, null=True, auto_now=True)
    data_exclusao            = models.DateTimeField(blank=True, editable=False, null=True)

    def __unicode__(self):
        return self.titulo
    
    @property
    def quantidade(self):
        return self.qtd_ofertas_por_pessoa
    
    @property
    def num_disponivel(self):
        num_vendido = Cupon.objects.filter(oferta=self.id).count()
        num_disponivel = self.qtd_ofertas - num_vendido
        return num_disponivel
    
    @property
    def num_vendido(self):
        num_vendido = Cupon.objects.filter(oferta=self.id).count()
        return num_vendido
    
    @property
    def percentagem_vendido(self):
        num_vendido = self.num_vendido()
        if num_vendido > self.fecha_em:
            return 100
        elif self.fecha_em:
            return int( ( (num_vendido*1.0) / self.fecha_em) * 100)
        else:
            return 0

    def num_necessario_fechamento(self):
        num_vendido = self.num_vendido()
        if num_vendido > self.fecha_em:
            return 0
        else:
            return self.fecha_em - num_vendido
        
    @property
    def tempo_restante(self):
        agora = datetime.datetime.now()
        expira_em = self.publicado_em + datetime.timedelta(hours=self.duracao_da_oferta)

        if expira_em < agora :
            return "Oferta fechada"

        tempo_expiracao =  expira_em - agora
        horas_tempo_expiracao = int(time.strftime("%H", time.gmtime(tempo_expiracao.seconds)))
        mins_tempo_expiracao = int(time.strftime("%M", time.gmtime(tempo_expiracao.seconds)))

        if tempo_expiracao.days < 1:
            if horas_tempo_expiracao < 1:
                if mins_tempo_expiracao < 1:
                    if tempo_expiracao.seconds < 1:
                        return "Oferta fechada"
                    else:
                        return "%d segundos" % tempo_expiracao.seconds
                else:
                    return "%d minutos" % mins_tempo_expiracao
            else:
                return "%d horas, %d minutos" % (horas_tempo_expiracao, mins_tempo_expiracao)

        else:
            if horas_tempo_expiracao < 1:
                return "%d dias" % (tempo_expiracao.days)
            else:
                return "%d dias, %d horas" % (tempo_expiracao.days, horas_tempo_expiracao)

    def esta_expirado(self):

massive002/templates/old/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

{% comment %}
MassiveCoupon - Base HTML Page
{% endcomment %}


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
    <link rel="shortcut icon" href="/media/images/favicon.ico" >

    <title>{% block title %}{% endblock title %} :: Ofertas Clipper</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <meta content="{% block metakeywords %}{{ page_metakeywords }}{% endblock metakeywords %}" name="Keywords"/>
    <meta content="{% block metadescription %}{{ page_metadescription }}{% endblock metadescription %}" name="Description"/>
    <meta content="en" http-equiv="Content-Language"/>
    <meta name="verify-v1" content="l4Z4jgwG5X58psxFkH3eILv9ua3nJKYrq5zGFZC0xj0=" />
    {% block metadata %}
    {% endblock metadata %}

    <link type="text/css" rel="stylesheet" href="/media/js/css/ui-lightness/jquery-ui-1.7.2.custom.css" />
    <link type="text/css" rel="stylesheet" href="/media/css/all.css" />
    <!--[if lt IE 8]><link rel="stylesheet" type="text/css" href="/media/css/lt8.css" /><![endif]-->

    {% block extralinks %}
    {% endblock extralinks %}
    <style type="text/css">
	    {% block extracss %}
	    {% endblock extracss %}
    </style>
 	<!-- <script src="http://code.jquery.com/jquery-1.5.js"></script> -->
    <script type="text/javascript" src="/media/js/jquery-1.3.2.min.js"></script>
    <script type="text/javascript" src="/media/js/jquery-ui-1.7.2.custom.min.js"></script>
    <script type="text/javascript" src="/media/js/jquery.watermarkinput.js"></script>
    <script type="text/javascript" src="/media/js/massivecoupon.js"></script>
    


    {% block extrascripts %}

    {% endblock extrascripts %}
    <script language="javascript">

  $(document).ready(function()
  {
    $("#user-msg-close").click(function () {
      $("#user-msg-div").hide();
      return false;
    });

    $("#city-slider-link").click(function () {
      $(".city-slider").slideToggle("slow");
      return false;
    });

    
  });

    {% block extrajs %}
    {% endblock extrajs %}

    </script>


</head>

<body>

  <div class="city-slider" style="display: none; overflow:hidden;">
   <ul>
     {% for cidade in cidades_disponiveis %}
       <li><a href="{% url cidade_index cidade_slug=cidade.slug %}">{{ cidade.nome }}</a></li>
     {% endfor %}
   </ul>
	
  </div>
<a href="" class="city-slider-link" id="city-slider-link"> Mostrar cidades </a>
  <div class="email-slider" style="display: none; overflow:hidden;">
  	
    <form>
      Email
    </form>
  </div>

  <div id="wrapper">

      {% block content %}{% endblock %}
                
  </div> <!-- end wrapper -->


</body>
</html>

massive002/templates/old/bid.html
{% extends "base.html" %}

{% block extralinks %}
   <link type="text/css" rel="stylesheet" href="/media/js/css/jquery.clockpick.1.2.7.css" />
{% endblock %}

{% block extracss %}

    div.fieldWrapper label {
      width: 180px;
    }


    #id_rate, #id_hourly_rate, #id_estimated_time  {
      width: 30px;
    }

    .qtip-content  {
        font-size: 10pt;
        font-weight: bold;
    }

    div.period1 div.fieldWrapper select#id_hourmin_start1 { 
      background: #eee;
      height: 30px;
      font-size: 130%;
    }

{% endblock %}

{% block extrascripts %}
  <script type="text/javascript" src="/media/js/jquery.clockpick.1.2.7.min.js"></script>
{% endblock %}

{% block extrajs %}

    var rate_type = 0;

    function submitForm()
    {
      $.Watermark.HideAll();
      $('#id_longitude').val(longitude);
      $('#id_latitude').val(latitude);
      $('#id_radius').val(radius);
      return true;
    }

    function change_rate_type(type)
    {
      if( type == 0 ) {
        $('div#toggle-estimated-time').show();
        rate_type = 0;
      }
      else {
        $('div#toggle-estimated-time').hide(); 
        rate_type = 1;
      }
    }

    function change_period(period)
    {
      if( period == 0 ) {
        $('div.period2').hide();
        $('div.period1').show();
      }
      else {
        $('div.period1').hide();
        $('div.period2').show();
      }
    }

    function CurrencyFormatted(amount)
    {
	var i = parseFloat(amount);
	if(isNaN(i)) { i = 0.00; }
	var minus = '';
	if(i < 0) { minus = '-'; }
	i = Math.abs(i);
	i = parseInt((i + .005) * 100);
	i = i / 100;
	s = new String(i);
	if(s.indexOf('.') < 0) { s += '.00'; }
	if(s.indexOf('.') == (s.length - 2)) { s += '0'; }
	s = minus + s;
	return s;
    }

    function update_estimated_quote()
    {
      var total = 0;

      if ( rate_type == 0 ) {
        if( parseFloat( $("#id_rate").val() ) > 0 && parseFloat( $("#id_estimated_time").val()) > 0 ) {
           total = parseFloat($("#id_rate").val()) * parseFloat($("#id_estimated_time").val()) ;
        }
      }
      else {
        if( parseFloat( $("#id_rate").val() ) > 0 ) {
          total = parseFloat( $("#id_rate").val() );
        }
      }

      $('#id_estimate').html('$' + CurrencyFormatted(total));

    }

    $().ready(function() 
    {

      $("#id_dates").change(function(){
        change_period(this.selectedIndex);
      });

      $("#id_rate_type").change(function(){
        change_rate_type(this.selectedIndex);
        update_estimated_quote();
      });


      $("#id_rate").keyup(function(){
        update_estimated_quote();
      });
      $("#id_hourly_rate").keyup(function(){
        update_estimated_quote();
      });
      $("#id_estimated_time").keyup(function(){
        update_estimated_quote();
      });


//      $("div.period1 div.fieldWrapper input#id_hourmin_start").selectbox();

//      {% if period2 %}
//      $("div.period2 div.fieldWrapper input#id_hourmin_start").selectbox();
//      {% endif %}

      // Focus and blur highlights
      $('div.fieldWrapper input')
        .focus(function(e) { $(e.target).addClass('focused'); })
        .blur(function(e) { $(e.target).removeClass('focused'); });


    //  create_toggle('[+] Add Hourly Rate', 'remove', 'toggle-hourly-rate');
      create_toggle('[+] Add Note', 'remove', 'toggle-note');

      // make enter work like tab
      $('div.fieldWrapper input').keypress(preventEnterSubmit);

      // Setup hint tooltips and error messages
      {% for f in form %}
      {% if f.help_text %}showHint('#{{ f.auto_id }}', '{{ f.help_text }}');{% endif %}
      {% if f.errors %}showError('#{{ f.auto_id }}', '{% for e in f.errors %}{{ e }}\n{% endfor %}', true);{% endif %}
      {% endfor %}

      // Focus on initial field
      //$('#id_service').focus();
    });

    function showHint(element, msg)
    {
      $(element).Watermark(msg);
      //return showTip(element, msg);
    }

    function showError(element, msg, immediate)
    {
      showReady = immediate ? true : false;
      return showTip(element, msg, { styleName: 'red', showReady: showReady, destroy: true });
    }

{% endblock %}

{% block content %}

<div style="font-size: 120%; color: #F19A20;">Job Offer for {{ service_request }}</div>
<div style="">Title: {{ service_request.title }}</div>
<div>Dek: {{ service_request.description }}</div>

{% comment %}
  flat_or_base_rate = forms.DecimalField(max_length=100, help_text="0")
  hourly_rate = forms.DecimalField(max_length=100, help_text="0")
  are_materials_included = forms.BooleanField(required=False, initial=True)
  date = forms.DateField( widget=forms.widgets.DateInput())

  hourmin_start = forms.ChoiceField(choices=HOURMIN, required=False, initial=19, widget=widgets.Select( attrs={'class':'sched_day_select'} ) )
  hourmin_end = forms.ChoiceField(choices=HOURMIN, required=False, initial=35, widget=widgets.Select( attrs={'class':'sched_day_select'} ))

  note = forms.CharField( widget=forms.widgets.Textarea() )
  customer_travel_required = forms.BooleanField(required=False, initial=False)
{% endcomment %}

<form id="bidform" method="POST" enctype="multipart/form-data" onSubmit="return submitForm();" class="form-body">

    <div class="form-label">Enter Your Price Quote  - <span>Time Remaining: {{ service_request.time_left }}</span></div>

    <div class="fieldWrapper">
        <label for="{{ form.rate.auto_id }}">How much do you charge? :</label> $ {{ form.rate }}  {{ form.rate_type}}
    </div>

    <div class="fieldWrapper" id="toggle-estimated-time">
        <label for="{{ form.estimated_time.auto_id }}">Estimated Time:</label>{{ form.estimated_time }} Hours
    </div>

    <div class="fieldWrapper" style="height: 30px; font-size: 140%;">
      <label>Estimated Quote:</label><div id="id_estimate" style="color: #3a3; font-size: 170%;">$0.00</div>
    </div>

    <div class="fieldWrapper">
        <label for="{{ form.are_materials_included.auto_id }}">Includes Parts & Materials:</label> {{ form.are_materials_included }}
    </div>

<br><br>
    {% if is_multiple_periods %}
      <div class="fieldWrapper">
        <label for="{{ form.dates.auto_id }}">Select Job Start Day:</label> {{ form.dates }}
      </div>
    {% else %}
      <div class="fieldWrapper">
        <label for="{{ form.dates.auto_id }}">Select Job Start Time on {{ start_date|date }}</label>
      </div>
    {% endif %}

    <div class="period1">
      <div class="fieldWrapper">
          <label for="{{ form.hourmin_start1.auto_id }}">Select your Start Time:  </label> {{ form.hourmin_start1 }}
      </div>
    </div>

    <div class="period2" style="display: none;">
      <div class="fieldWrapper">
          <label for="{{ form.hourmin_start2.auto_id }}">Select your Start Time:  </label> {{ form.hourmin_start2 }}
      </div>
    </div>

    <br><br>
    <div>Add a note for {{ service_request.user|capfirst }}</div>
    <div class="help-list toggle-note">
        <label for="{{ form.note.auto_id }}">Note:</label>{{ form.note }}
    </div>

    <div class="fieldWrapper">
        <label for="{{ form.customer_travel_required.auto_id }}">Customer Should Travel to My Place of Business:</label> {{ form.customer_travel_required }}
    </div>

    <br><br>
    <div class="form-label">
        &gt;&gt;&gt; <input type="submit"  value="Submit Quote" alt="Continue" id="button_continue"/> to next step...
    </div>

</form>

<div><a href="/reject_request/">No Thanks, I'm not interested</a></div>

{% endblock %}

massive002/templates/old/footer.html
{% load i18n %}

<div id="footer">
    This is the footer
</div>

massive002/templates/old/header.html
{% load i18n %}

<div id="header">
    This is the header
</div>